import type { LabTable } from "@/systems/lab";
import type { BandForm, BandGroup, BandMode, PresetId } from "@/systems/dock";
import type { BarKind, CheckId } from "./model";

const en = {
  // Bar and quick controls
  presets: {
    stack: "Stack",
    tray: "Tray",
    scroll: "Band scroll",
    swap: "Either / or",
  } satisfies Record<PresetId, string>,
  custom: "Custom",
  meta: (config: string, n: number, mode: string) => `${config} · ${n} in the Dock · ${mode}`,
  // Knobs
  compose: "Composition",
  composeNote:
    "The band is not one strategy but a few independent choices, and each is an overflow strategy: while the bar and every occupant as a pill fit side by side, they just stand side by side. The presets are named sets of choices; change any knob and it is yours.",
  share: "Share the band",
  shareNote: "Off is the old way: the pills centred, the bar pinned in a row under them. What ships is Either / or.",
  group: "Occupants beside the bar",
  groups: {
    all: "All",
    tray: "Tray",
    count: "Count",
  } satisfies Record<BandGroup, string>,
  groupNotes: {
    all: "In one row after the bar, as many as there are; the bar gives up their width down to its minimum, and the rest scroll.",
    tray: "In a window of a fixed size at the end. The bar's share never depends on the count; the window scrolls inside itself.",
    count: "Folded into one ball with how many. Tap it: the bar folds to a ball and the occupants open out, scrolling if they need to.",
  } satisfies Record<BandGroup, string>,
  form: "Shape, beside the bar",
  openForm: "Shape, opened",
  forms: { pill: "Pill", ball: "Ball" } satisfies Record<BandForm, string>,
  trayCap: "Tray holds, on a phone",
  trayCapHint: (n: number) => `${n} · ${n + 2} wider`,
  peek: "Peek the next",
  peekNote: "A window that holds more than it shows ends on half of the next, so the cut says it scrolls.",
  barScrolls: "The bar scrolls with them",
  barScrollsNote: "One strip, edge to edge: the bar first, sliding away as the occupants are swiped in.",
  // Bar
  bar: "Pinned bar",
  bars: {
    lab: "Lab bar",
    prompt: "/prompt",
    works: "/works",
    none: "None",
  } satisfies Record<BarKind, string>,
  // Occupants
  occupants: "Occupants",
  occupantsNote: "All real: the Dock's own LiveActivity with stand-in content, the music pill from the offline player, a parked app window.",
  samples: "Sample activities",
  music: "Play music",
  window: "Park a window",
  notice: "Fire a notice",
  // Readout
  readout: "The four rules",
  close: "Close",
  readoutNote: "Measured off the page as it is now: the real Dock, the real bar.",
  modes: {
    stack: "stacked",
    fit: "side by side",
    all: "in a row",
    tray: "in a tray",
    count: "counted",
    open: "opened",
  } satisfies Record<BandMode, string>,
  notMet: "The bar has not met the band. Scroll.",
  noBar: "No pinned bar on the page: the Dock is the Dock.",
  empty: "Nothing in the Dock. Add a sample activity.",
  checks: {
    oneBand: "One band",
    barUsable: "Bar usable",
    noOverlap: "No overlap",
    reachable: "All reachable",
  } satisfies Record<CheckId, string>,
  checkNotes: {
    oneBand: "Everything shares the top row; nothing stacks under it.",
    barUsable: "The bar keeps at least the width it can do its job in.",
    noOverlap: "Nothing that takes a tap is under anything else; the gap holds.",
    reachable: "Every occupant is in sight, a swipe away in a window that scrolls, or behind the count.",
  } satisfies Record<CheckId, string>,
  swipeAway: (n: number) => `${n} a swipe away`,
  tapAway: (n: number) => `${n} behind the count`,
  gapIs: (px: number) => `gap ${px}px`,
  barIs: (w: number, min: number) => `bar ${w} / min ${min}px`,
  // Page
  pageTitle: "The page",
  pageNote:
    "Scroll until the bar meets the Dock. Which bar is the second row of the lab's own bar: the lab bar itself (two rows on a phone), or the real /prompt or /works toolbar with sample facets, pinned below.",
  pin: "Scroll to where it pins",
  top: "Back to the knobs",
  rowTitle: (i: number) => `Entry ${i + 1}`,
  noticeTitle: "Dark Mode",
  noticeNote: "Following the Sun",
};

const zh: typeof en = {
  presets: {
    stack: "上下叠放",
    tray: "小球托盘",
    scroll: "整条横滑",
    swap: "二选一",
  },
  custom: "自定义",
  meta: (config: string, n: number, mode: string) => `${config} · Dock 里 ${n} 项 · ${mode}`,
  compose: "组合",
  composeNote: "顶部带不是一种固定策略，而是几个互相独立的选择，而且每一个都是溢出策略：工具栏和所有胶囊并排放得下时，就直接并排放。预设只是给其中几组起了名字；动任何一个旋钮，它就是你自己的组合。",
  share: "共用顶部带",
  shareNote: "关掉就是以前的做法：胶囊在顶部居中，工具栏固定在它们下面的第二行。线上默认是“二选一”。",
  group: "活动怎么站在工具栏旁边",
  groups: {
    all: "全部",
    tray: "托盘",
    count: "计数",
  },
  groupNotes: {
    all: "全部排成一行跟在工具栏后面；工具栏让出它们的宽度，最多让到自己的最小宽度，放不下的横滑。",
    tray: "住在末端一个固定大小的窗口里。工具栏分到的宽度不随数量变化；窗口内部自己横滑。",
    count: "收成一个显示数量的小球。点它：工具栏收成小球，活动展开，需要时可以横滑。",
  },
  form: "在工具栏旁边的形状",
  openForm: "展开后的形状",
  forms: { pill: "胶囊", ball: "小球" },
  trayCap: "手机上托盘放几个",
  trayCapHint: (n: number) => `${n} · 更宽时 ${n + 2}`,
  peek: "露出下一个的一半",
  peekNote: "窗口装的比露出来的多时，末尾停在下一个的一半上，这道切口说明它能滑。",
  barScrolls: "工具栏跟着一起滑",
  barScrollsNote: "一整条，贴着屏幕两边：工具栏在最前，活动滑进来时它滑出去。",
  bar: "吸顶工具栏",
  bars: {
    lab: "实验室工具栏",
    prompt: "/prompt",
    works: "/works",
    none: "无",
  },
  occupants: "顶部的住户",
  occupantsNote: "全是真的：Dock 自己的 LiveActivity（内容是替身）、离线播放器带出的音乐胶囊、一个停靠的应用窗口。",
  samples: "示例活动",
  music: "播放音乐",
  window: "停靠一个窗口",
  notice: "发一条提示",
  readout: "四条规则",
  close: "关闭",
  readoutNote: "直接从页面上量出来：真实的 Dock，真实的工具栏。",
  modes: {
    stack: "上下叠放",
    fit: "并排放得下",
    all: "排成一行",
    tray: "在托盘里",
    count: "收成计数",
    open: "已展开",
  },
  notMet: "工具栏还没碰到顶部带。往下滚。",
  noBar: "页面上没有吸顶工具栏：Dock 就是 Dock。",
  empty: "Dock 里没有东西。加一个示例活动。",
  checks: {
    oneBand: "只占一条",
    barUsable: "工具栏可用",
    noOverlap: "没有重叠",
    reachable: "都够得到",
  },
  checkNotes: {
    oneBand: "所有东西共用顶部这一行，没有叠到下面去的。",
    barUsable: "工具栏至少保住它能正常工作的宽度。",
    noOverlap: "能点的东西不会压在别的东西下面；间距保得住。",
    reachable: "每个住户要么看得见，要么在能滑的窗口里滑一下就到，要么在计数后面。",
  },
  swipeAway: (n: number) => `${n} 个需滑动`,
  tapAway: (n: number) => `${n} 个在计数后面`,
  gapIs: (px: number) => `间距 ${px}px`,
  barIs: (w: number, min: number) => `工具栏 ${w} / 最小 ${min}px`,
  pageTitle: "页面",
  pageNote: "往下滚，直到工具栏碰到 Dock。用哪个工具栏在实验室工具栏的第二行选：实验室工具栏自己（手机上两行），或者下面固定的真实 /prompt、/works 工具栏（数据是示例）。",
  pin: "滚到它固定的地方",
  top: "回到旋钮",
  rowTitle: (i: number) => `第 ${i + 1} 条`,
  noticeTitle: "深色模式",
  noticeNote: "跟随日出日落",
};

export const BAND_STRINGS: LabTable<typeof en> = { en, zh };
export type BandStrings = typeof en;
