import type { Locale } from "@/lib/i18n";
import { ASK_SUGGESTIONS } from "./prompts";

// Ask's words, in both languages. Kept with the system, as the labs keep
// theirs, rather than in the site-wide table. The suggested questions are
// ./prompts.ts, with the rest of what is written for the model.

const en = {
  ask: "Ask",
  askRow: "Ask AI",
  placeholder: "Ask me anything…",
  backToSearch: "Back to search",
  newChat: "New chat",
  model: "Model",
  thinking: "Thinking…",
  steps: "Looked through the site",
  searched: (q: string) => `Searched “${q}”`,
  read: (title: string) => `Read ${title}`,
  results: (n: number) => (n === 1 ? "1 passage" : `${n} passages`),
  noResults: "Nothing matched",
  emptyTitle: "Hey, I’m Hux. Ask me anything.",
  emptyHint: "Well, the AI me. The real one is @Huxpro on X.",
  error: "Something went wrong.",
  retry: "Try again",
  history: "History",
  sidebar: "Sidebar",
  noHistory: "Past conversations show up here. They stay in this browser.",
  deleteChat: "Delete conversation",
  copy: "Copy",
  copied: "Copied",
  regenerate: "Regenerate",
  edit: "Edit",
  editSend: "Send",
  editCancel: "Cancel",
  rewind: "Rewind to here",
  rewindConfirm: "Drop what follows?",
  effort: "Thinking",
  efforts: { low: "Quick", medium: "Balanced", high: "Deep" },
  close: "Close Ask",
  openAsk: "Open the conversation",
  collapse: "Collapse",
  minimize: "Minimize to the Dock",
  searching: (q: string) => `Searching “${q}”…`,
  reading: (title: string) => `Reading ${title}…`,
  placement: "Where Ask sits",
  placements: { center: "Center", side: "Side", top: "Top" },
  dragHint: "Drop to dock Ask here",
  suggestions: ASK_SUGGESTIONS.en,
  kinds: {
    post: "Post",
    conviction: "Conviction",
    influence: "Influence",
    era: "Era",
    language: "Language",
    talk: "Talk",
    project: "Project",
    press: "Press",
    event: "Event",
    role: "Role",
    work: "Work",
  } as Record<string, string>,
  watch: "Watch",
  slides: "Slides",
  photos: "Photos",
  link: "Link",
  contextRemove: "Don't send this with the question",
  contextSent: "Sent with the question",
  dropHint: "Drop to ask about it",
  askSelection: "Ask about this",
};

type AskStrings = typeof en;

const zh: AskStrings = {
  ask: "问答",
  askRow: "问 AI",
  placeholder: "问我点什么…",
  backToSearch: "返回搜索",
  newChat: "新对话",
  model: "模型",
  thinking: "思考中…",
  steps: "翻阅了网站",
  searched: (q) => `搜索「${q}」`,
  read: (title) => `阅读《${title}》`,
  results: (n) => `${n} 段`,
  noResults: "没有匹配",
  emptyTitle: "嗨，我是黄玄，问什么都行。",
  emptyHint: "嗯，这是 AI 版的我。本人在 X 上 @Huxpro。",
  error: "出了点问题。",
  retry: "重试",
  history: "历史",
  sidebar: "侧边栏",
  noHistory: "过往的对话会出现在这里，只保存在这个浏览器中。",
  deleteChat: "删除对话",
  copy: "复制",
  copied: "已复制",
  regenerate: "重新生成",
  edit: "编辑",
  editSend: "发送",
  editCancel: "取消",
  rewind: "回到这里",
  rewindConfirm: "删掉之后的对话？",
  effort: "思考",
  efforts: { low: "快速", medium: "均衡", high: "深入" },
  close: "关闭问答",
  openAsk: "打开对话",
  collapse: "收起",
  minimize: "收进 Dock",
  searching: (q) => `正在搜索「${q}」…`,
  reading: (title) => `正在阅读《${title}》…`,
  placement: "问答的位置",
  placements: { center: "居中", side: "侧边", top: "顶部" },
  dragHint: "松手，问答停在这里",
  suggestions: ASK_SUGGESTIONS.zh,  kinds: {
    post: "文章",
    conviction: "信念",
    influence: "影响",
    era: "时期",
    language: "语言",
    talk: "演讲",
    project: "项目",
    press: "报道",
    event: "活动",
    role: "职位",
    work: "作品",
  },
  watch: "观看",
  slides: "幻灯片",
  photos: "照片",
  link: "链接",
  contextRemove: "不随问题发送",
  contextSent: "随问题发送",
  dropHint: "放下，问问它",
  askSelection: "问问这段",
};

export function askStrings(locale: Locale): AskStrings {
  return locale === "zh" ? zh : en;
}
